### ISSUE TITLE
using set_interrupt_handler does not terminate the run

### ISSUE THREAD

**Issue by itribs** [DelSkayn/rquickjs#102] opened 2023-01-10 16:12 UTC
```rust
async fn delay(msec: u32) {
    let duration = std::time::Duration::from_millis(msec as _);
    tokio::time::sleep(duration).await;
}

#[tokio::main]
async fn main() {
    let rt = rquickjs::Runtime::new().unwrap();
    let ctx = rquickjs::Context::full(&rt).unwrap();

    rt.spawn_executor(rquickjs::Tokio);

    rt.set_interrupt_handler(Some(Box::new(|| {
            println!("check");
            false
    })));

    ctx.with(|ctx| {
        let global = ctx.globals();
        global.set("delay",
            rquickjs::Func::from(|msec| Promised(delay(msec)))
        ).unwrap();
        global.set("println", Func::from(|msg: String| println!("{:?}", msg)))
                .unwrap();
    });

    let res: Promise<()> = ctx.with(|ctx| {
        ctx.eval(r"
                async function cycles() { 
                        while(true) { 
                                await delay(1000);
                                println("test------");
                        }
                } 
                cycles(); 
                ").unwrap()
    });
    res.await.unwrap();
    rt.idle().await;
}
```
 the closure in 'set_interrupt_handler' will not be called

**Comment by DelSkayn** [comment] 2023-02-03 22:03
Hi, Thanks for the bug report.

I am having some trouble with how to handle this issue.
What was the behavior you expected from this code?
I personally have been able to get the interrupt handler to run.

The interrupt handler is functionality from quickjs, which runs every so often while executing javascript, more specifically quickjs executes the interrupt handler once it has executed a certain number of instructions.
Because the example spends most of its time sleeping, it will take a rather long time before the interrupt handler is called.
Adding some work to the loop in javascript like for instance:
```javascript
async function cycles() { 
    while(true) { 
        for(let i = 0;i < 100000;i++){}
        await delay(1000);
        println('test- -----');
    }
} 
cycles(); 
```
will cause the interrupt handler to fire more often.

**Comment by itribs** [comment] 2023-02-04 03:37
Hi, thank you very much for your reply.

In short I have embedded rquickjs in my project to execute external scripts, which are always untrustworthy and I need the ability to terminate the script run in case the wrong use in the script causes the resources to never be released.

Currently I have no choice but to use rusty_v8 instead, which is a huge library with similar problems, but he only needs to execute a little bit of JavaScript before and after the 'delay' method, e.g.
```
var a=0;
await delay(1000);
a+=1;
```
This would break the loop and I would be ok with wrapping a layer in each rust method to add a little extra script.

This approach I tried in rquickjs does not work, you may have to give the engine enough time to execute the interrupt handler as you did, but this approach is too costly.

**Comment by felixmaker** [comment] 2023-03-24 09:21
When I run the following code:
```
use rquickjs::bind;

#[bind(object)]
async fn sleep(msec: u64) {
    let duration = std::time::Duration::from_millis(msec);
    tokio::time::sleep(duration).await
}

#[tokio::main]
async fn main() {
    let rt = rquickjs::Runtime::new().unwrap();
    let ctx = rquickjs::Context::full(&rt).unwrap();

    rt.spawn_executor(rquickjs::Tokio);

    ctx.with(|ctx| {
        ctx.globals().init_def::<Sleep>().unwrap();
    });
}
```

It ends with panic: 
```
PS C:\Users\Felixmaker\Desktop\demo-qjs> cargo run
   Compiling demo-qjs v0.1.0 (C:\Users\Felixmaker\Desktop\demo-qjs)
    Finished dev [unoptimized + debuginfo] target(s) in 2.46s
     Running `target\debug\demo-qjs.exe`
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`', C:\Users\Felixmaker\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2\rquickjs-core-0.1.7\src\runtime\async_runtime.rs:41:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\demo-qjs.exe` (exit code: 101)
```.

Same panic when run your example. If I use `async-std`, it does not panic.

Do you know why? Thanks!

**Comment by katyo** [comment] 2023-03-24 17:04
@felixmaker What tokio features are you enabled?

**Comment by felixmaker** [comment] 2023-03-25 03:01
@katyo Thank you! It works!

**Comment by DelSkayn** [comment] 2023-05-24 11:28
Closing this issue as the behavior described in the issue is as intended.

**Closed by DelSkayn** 2023-05-24 11:28 UTC
Labels: bug
