### ISSUE TITLE
Unable to build for x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by tobiemh** [DelSkayn/rquickjs#76] opened 2022-08-11 11:44 UTC
I'm trying to build a library for `x86_64-pc-windows-msvc` which uses rquickjs as a dependency.

The features that I currently have enabled are as follows (i've tried with and without the `bindgen` feature):
```toml
["bindgen", "classes", "futures", "loader", "macro", "properties", "parallel"]
```

When building in the windows-latest platform of Github Actions I am receiving the following error

```bash
error: failed to run custom build command for `rquickjs-sys v0.1.6`
Error: failed to run custom build command for `rquickjs-sys v0.1.6`
# ... lots of warnings ...
D:\a\build\build\target\x86_64-pc-windows-msvc\release\build\rquickjs-sys-c9a934b275fe053a\out\quickjs.c(41979): error C2099: initializer is not a constant
# ... lots of warnings ...
error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-W4" "-D_GNU_SOURCE" "-DCONFIG_VERSION=\"2020-01-19\"" "-DCONFIG_BIGNUM" "-DCONFIG_MODULE_EXPORTS" "-FoD:\\a\\build\\build\\target\\x86_64-pc-windows-msvc\\release\\build\\rquickjs-sys-c9a934b275fe053a\\out\\quickjs.o" "-c" "D:\\a\\build\\build\\target\\x86_64-pc-windows-msvc\\release\\build\\rquickjs-sys-c9a934b275fe053a\\out\\quickjs.c" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

The tooling versions I am using are:
```
go version go1.17.12 windows/amd64
cargo 1.62.1 (a748cf5a3 2022-06-08)
rustc 1.62.1 (e092d0b6b 2022-07-16)
cmake version 3.23.3
gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0
g++.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0
perl v5.32.1 built for MSWin32-x64-multi-thread
```

The full build failure can be seen here: https://github.com/surrealdb/build/runs/7783510797

I've looked at the `github/workflows/ci.yml` file, and I'm not doing anything differently from that setup/environment. In addition there appears to be no issue when compiling for the `x86_64-pc-windows-gnu` target in the windows-latest Github Action.

Is there something I'm missing to get rquickjs to build for the `x86_64-pc-windows-msvc` target?

**Comment by DelSkayn** [comment] 2022-08-12 14:52
Hmmm, This is a weird one. 

It seems that when compiling with release mode with msvc the `log2` function from `math.h` is no longer a function ([build](https://github.com/DelSkayn/rquickjs/runs/7808144627?check_suite_focus=true)).
It compiles fine in debug mode and on release mode when targeting `i686-pc-windows-msvc`.

Maybe the visual studio compiler implements `log2` with a macro when optimizations are enabled?

**Comment by tobiemh** [comment] 2022-08-12 15:20
@DelSkayn apologies I'm not a Windows user in any way (just trying to build for Windows in addition to Linux/macOS). You're definitely going to understand more about this than I am.

It's not massively urgent as it does build for the `x86_64-pc-windows-gnu` target.

**Comment by tobiemh** [comment] 2022-08-15 19:22
I've just seen #42 which I presume is the same issue, but even though #43 has been merged, this issue has resurfaced.

**Comment by DelSkayn** [comment] 2022-08-16 16:54
> I've just seen #42 which I presume is the same issue, but even though #43 has been merged, this issue has resurfaced.

Oh, good catch! I had forgotten about that issue and it also has fix!

I implemented the fix in #77 and also added the problematic build target to our CI to catch future regressions.

**Comment by DelSkayn** [comment] 2022-08-16 21:56
Closing as the issue should be resolved.

**Closed by DelSkayn** 2022-08-16 21:56 UTC

**Comment by felixmaker** [comment] 2023-03-23 11:05
Today, I still get this error:

```bash
PS C:\Users\Felixmaker\Desktop\demo-quickjs> cargo run
   Compiling rquickjs-sys v0.1.7
error: failed to run custom build command for `rquickjs-sys v0.1.7`                                                            

Caused by:
  process didn't exit successfully: `C:\Users\Felixmaker\Desktop\demo-quickjs\target\debug\build\rquickjs-sys-d4a5dbf211ae4feb\build-script-build` (exit code: 1)
  --- stderr


  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MT" "-Z7" "-Brepro" "-W4" "-D_GNU_SOURCE" "-DCONFIG_VERSION=\"2020-01-19\"" "-DCONFIG_BIGNUM" "-DCONFIG_MODULE_EXPORTS" "-FoC:\\Users\\Felixmaker\\Desktop\\demo-quickjs\\target\\debug\\build\\rquickjs-sys-9b2da068de74161e\\out\\850d1cd04298eee0-libregexp.o" "-c" "C:\\Users\\Felixmaker\\Desktop\\demo-quickjs\\target\\debug\\build\\rquickjs-sys-9b2da068de74161e\\out\\libregexp.c" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

How to solve it?

**Comment by DelSkayn** [comment] 2023-03-23 13:58
Hi, Could you maybe provide a more detailed error?

`"cl.exe" did not execute successfully (status code exit code: 2).` often means that quickjs didn't compile correctly but your error contains no compilation errors. Could you maybe rerun with the verbose flag?

In the mean time our CI seems to be able to build the library without problems on windows so it could be a problem in your build environment.

**Comment by felixmaker** [comment] 2023-03-23 16:50
> Hi, Could you maybe provide a more detailed error?
> 
> `"cl.exe" did not execute successfully (status code exit code: 2).` often means that quickjs didn't compile correctly but your error contains no compilation errors. Could you maybe rerun with the verbose flag?
> 
> In the mean time our CI seems to be able to build the library without problems on windows so it could be a problem in your build environment.

```
  --- stderr
  thread 'main' panicked at 'Unable to apply patch: Os { code: 232, kind: BrokenPipe, message: "管道正在被关闭。" }', C:\Users\Felixmaker\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2\rquickjs-sys-0.1.7\build.rs:142:33
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Oh, I find out where I am wrong! I copy the `patch.exe` directly from `C:\Program Files\Git\usr\bin` to a folder that is in PATH. In fact, the `patch.exe` in `C:\Program Files\Git\usr\bin` needs `msys-2.0.dll` as its dependency.

Finally, I run the program on successfully! It works well!

Thank you!
